### ISSUE TITLE
ModuleNotFoundError: No module named 'mathics_django.server'

### ISSUE THREAD

**Issue by kxxt** [Mathics3/mathics-django#10]
Hi, after installing from pip, the command mathicsserver throws an error:
```
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\mathicsserver.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'mathics_django.server'
```
There is already [an issue opened in Mathics](https://github.com/mathics/Mathics/issues/1110).
It seems I'm not the only one encountering this issue.

**Comment by kxxt** [comment]
Looking into the mathics_django folder, there's only a web folder.
__init__.py, server.py, manage.py and more are all missing.
Maybe it's an issue in packaging.

**Comment by russellb23** [comment]
Encountering the same issue. Python 3.9.1 llvmlite 10 and Mathics3. `mathics` and `mathicsscript` works fine. Only Web based interface issue. As @kxxt reported looks like a packing issue.

**Comment by GarkGarcia** [comment]
@rocky I imagine this is similar to https://github.com/Mathics3/mathics-django/issues/6, `mathics_django.server` was incorrectly removed from `setup.py`.

**Comment by GarkGarcia** [comment]
@kxxt Weird, I just tried installing from source and it worked... Could you try cloning the repository and installing with `sudo make install` and tell me if the same error occurs? I suspect the issue was already fixed at some point but the version of the code in PyPI isn't up-to-date.

**Comment by GarkGarcia** [comment]
> Encountering the same issue. Python 3.9.1 llvmlite 10 and Mathics3. `mathics` and `mathicsscript` works fine. Only Web based interface issue. As @kxxt reported looks like a packing issue.

Which OS are you using?

**Comment by GarkGarcia** [comment]
> Could you try cloning the repository and installing with `sudo make install` and tell me if the same error occurs?

You would have to install the developer version of Mathics too though (v2.0.0.dev).

**Comment by kxxt** [comment]
@GarkGarcia Installing from source works fine.
Operating system : windows 10
I tried install it with pip in wsl and raspberrypi,  the same issue occured, too.

**Comment by GarkGarcia** [comment]
> @GarkGarcia Installing from source works fine.
> Operating system : windows 10
> I tried install it with pip in wsl and raspberrypi, the same issue occured, too.

Thanks! As a fine test, could you install it with pip from the git repository? You just need to uninstall your current installation and run the following run the following:

```
pip install git+https://github.com/Mathics3/mathics-django.git
```

**Comment by kxxt** [comment]
> > @GarkGarcia Installing from source works fine.
> > Operating system : windows 10
> > I tried install it with pip in wsl and raspberrypi, the same issue occured, too.
> 
> Thanks! As a fine test, could you install it with pip from the git repository? You just need to uninstall your current installation and run the following run the following:
> 
> ```
> pip install git+https://github.com/Mathics3/mathics-django.git
> ```

It works fine.

**Comment by kxxt** [comment]
I think something is missing in the packed `.whl` file in pypi ( some `.py` files) .

**Comment by rocky** [comment]
We haven't released wheel (egg, tarball, zip) for this.

**Comment by kxxt** [comment]
I mean on the pypi.
https://pypi.org/project/Mathics-Django/#files

**Comment by kxxt** [comment]
![image](https://user-images.githubusercontent.com/18085551/106404265-25efcd80-63e7-11eb-801c-7d5b18dec806.png)
There's only a web folder in it.
As you can see, a lot of source files are missing.
![image](https://user-images.githubusercontent.com/18085551/106404316-4881e680-63e7-11eb-8304-81d7c2256abc.png)

**Comment by rocky** [comment]
Right now we are in the process of splitting things up and you'll have to use git, not Pypi for all of the Mathics-related depencies. 

When 2.0 release is done, that might change. However there are more changes like this planned so that means this policy might continue for a while. 

If you want something post 1.1.1, use the [dockerhub image](https://hub.docker.com/r/mathicsorg/mathics).

**Comment by kxxt** [comment]
> Right now we are in the process of splitting things up and you'll have to use git, not Pypi for all of the Mathics-related depencies.
> 
> When 2.0 release is done, that might change. However there are more changes like this planned so that means this policy might continue for a while.
> 
> If you want something post 1.1.1, use the [dockerhub image](https://hub.docker.com/r/mathicsorg/mathics).

But this bug is about the 1.1.1 version of mathics-django.

After installing from pypi, I can't use it, getting the `ModuleNotFoundError`, which is very inconvenient.

Could anyone fix this issue?😅

**Comment by rocky** [comment]
The last stable release of Mathics, 1.1.1 doesn't require mathics-django -  it is built in. 

So use the last release of Mathics, 1.1.1. (You could aslo remove mathics-django but it shouldn't be imported at all in Mathics3, so it really doesn't matter.)

**Comment by kxxt** [comment]
Oh, I didn't notice that Mathics has included mathics-django, maybe it's time to update documentation .

Please close this issue if you want.
