### ISSUE TITLE
django.db.utils.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by ouening** [Mathics3/mathics-django#137]
OS: Ubuntu20.04
I installed mathics-django from source. But when I run the `make runserver` command, the error occurs as the title said.  Can someone help me?

**Comment by rocky** [comment]
I suspect the name of the file it was trying to open was reported as well, correct? 

And there was a Python traceback (google this if you don't know what that means or looks like).  

The thing about reporting problems is that generally you need to give all of the details.

**Comment by ouening** [comment]
I install it through `sudo python setup.py install` command instead of `make`, and it works after installation. Maybe the permission problem?
