### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by clemmrich** [Mathics3/mathics-django#144]
After installation  on Ubuntu (both using Mathics-omnibus and Mathics_Django) I cannot start mathicsserver, instead I get an error message:
ImportError: cannot import name 'url' from 'django.conf.urls' (/home/user/.local/lib/python3.9/site-packages/django/conf/urls/__init__.py)
error: failed to create database
This happens both on an installation with an older version of mathics and on a clean install of Ubuntu

**Comment by TiagoCavalcante** [comment]
This was fixed in PR #143. @rocky I think we should release Mathics Django 4.0.2 to fix this.

**Comment by rocky** [comment]
@TiagoCavalcante we can put out a small Mathics-Django release over the weekend. Given this, we might want to see if we could update threejs as well. Let me know what you decide there.

**Comment by clemmrich** [comment]
Thanks, as a workaround I manually replaced the two urls.py and it worked afterwards, so my problem is indeed identical to #143.
