### ISSUE TITLE
Mathics loads definitions from previous worksheets

### ISSUE THREAD

**Issue by GarkGarcia** [Mathics3/mathics-django#3]
This is a follow up to https://github.com/mathics/Mathics/issues/510:

> Steps to reproduce:
> 
>     1. Clone current master of Mathics.
> 
>     2. Install with `sudo python setup.py install`.
> 
>     3. Launch `mathicsserver`.
> 
>     4. Evaluate `a`.
> 
> 
> Result:
> `1`
> 
> ???

**Comment by danielpyon** [comment]
How does one delete a worksheet?

**Comment by rocky** [comment]
Everything seems to be stored in the SQLite datbase. The database location is shown when you run mathicsserver: 

```$ mathicsserver
mathicsserver
Migrating database /tmp/.local/var/mathics/mathics.sqlite
Operations to perform:
  Apply all migrations: auth, contenttypes, sessions, sites, web
Running migrations:
  No migrations to apply.

database initialized sucessfully

Django front end version 2.0.2.dev0
Mathics 2.0.1.dev
on CPython 3.8.7 (default, Feb 27 2021, 12:08:19) 
using SymPy 1.7.1, mpmath 1.2.1, django 3.1.5, cython 0.29.21

...
```

Looking at this in sqlite3: 

```
$ sqlite3 /home/rocky/.local/var/mathics/mathics.sqlite
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> .tables
auth_group                  django_content_type       
auth_group_permissions      django_migrations         
auth_permission             django_session            
auth_user                   django_site               
auth_user_groups            web_query                 
auth_user_user_permissions  web_worksheet             
sqlite> select * from django_content_type
   ...> ;
1|auth|permission
2|auth|group
3|auth|user
4|contenttypes|contenttype
5|sessions|session
6|sites|sitehttps://github.com/Mathics3/mathics-django/wiki
7|web|query
8|web|worksheet
sqlite> 
```

If you dump `webworksheet` you'll see lots of data. More than that I haven't investigated. (And even this much isn't of much interest to me right now.)  But hey, this is open source so feel free to do your own further investigations and report back what you find. You could add this for example to the wiki https://github.com/Mathics3/mathics-django/wiki .

**Comment by danielpyon** [comment]
That makes sense, thank you.

**Comment by rocky** [comment]
There is a misunderstanding of how the Django interface works. Reloading the URL doesn't reset values, it resets your _output display_.  Your worksheet is the same as it was before. 
No values are saved in the database. They are in your current session. 

We don't have a command or button to clear a worksheet and start with a new one. If you restart the _server_ well, then the worksheet doesn't persist, and you start with a fresh worksheet.

If you want to open an issue for a _feature_ to clear a worksheet. Ok. But this is independent of reloading the _display_.
