### ISSUE TITLE
Cell Output Area flicker in (re)evaluation

### ISSUE THREAD

**Issue by rocky** [Mathics3/mathics-django#54]
Since upgrading to the new MathJax, we get lots of re-evaluations in cell data and this causes lots of flickering in the cell area of the display.

Part of this may be caused by the fact that we evaluate twice in some circumstances, I think: once because of the stupid format done automatically, and once done when we realize that's not the format we want.

Part of this may be caused by MathJax's preview mode.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky any idea on how to fix this?

**Comment by rocky** [comment]
We have reduced some of this by not using MathJax in SVG and graphics3d output.

Another approach is to turn off MathJax's preview mode.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky do you think we should do it?

For me after disabling it, Mathics Django has became much better to use.
