### ISSUE TITLE
Remove MathML boxing for 3D Graphics

### ISSUE THREAD

**Issue by rocky** [Mathics3/mathics-django#66]
Right now 3D Graphics is is embedded inside MathML with other ugly magic done inside the embedding. 
MathJax gets in the way in its additional functions for zooming or showing the original. Instead it would be nice to have javascript controls in place instead.

Instead what we'd like is 3D graphics to be Javascript with JSON data for the image using three.js

To this end, I have created branch [mathml-removal-in-3d-graphics](https://github.com/Mathics3/mathics-django/tree/mathml-removal-in-3d-graphics). 

_This branch needs to be used with the [branch json-graphics of Mathics](https://github.com/Mathics/mathics/tree/json-graphics.)_  That branch adds a conversion function for Graphics3D object which will return either the JSON data or this wrapped in a psuedo Javascript `<script>` tag. 

The branch mathml-removal-in-3d-graphics does two things. On the Python side, in `format.py` it sees that the Mathics Expression returned is a Graphics3D object. This causes it to evaluate the result in MathMLForm. (This is a real misnomer for having the Mathics Expression expanded into to a Mathics expression that is destined for Three.js.). And then `to_json()` is called which causes more low-level formatting for JSON or JS-like objects. 

The other file changed `mathics.js` sees a `<script>` tag and tries to convert that to something. This part is not working. 

@TiagoCavalcanteTrindade I could really use your expertise and help here.  Is this something that would be of interest to you? 

(Right now I have other work I need to get to for the next 6 hours or so.)

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I was thinking if it really need a change in JavaScript, because of in the `graphics3d.js` file we are handling with a JSON without MathML, shouldn't the changes only the in the backend side?

Also I saw in the Network tab of Dev Tools the JSON still has MathML, then I checked the code and saw this:
```py
format = "System`MathMLForm"
```
(format.py line 89)

I guess another form should be created in Mathics core, e.g.: ``System`Graphics3DForm``, shouldn't it? Or maybe something built in Mathics Django backend to transform the Python object into a JSON?

**Comment by rocky** [comment]
> @rocky I was thinking if it really need a change in JavaScript, because of in the `graphics3d.js` file we are handling with a JSON without MathML, shouldn't the changes only the in the backend side?

You'd think if things were designed right, that would be the case, but no. 

One of the big big problems with this code base is that everything has smashed into one monolithic mess with unhelpful names like "XML" (for MathML) and "data" (for who knows what) and "apply_1", "apply_2" and little in the way of comments, docstrings or documents describing what's up.  (Some of the generic-ness of the names and the lack of documentation I have been slowly trying to address but there are mountains and mountains of this that is has taken months and will continue to take months.)

I find that any time I try to disentangle something I run into the fact that if you can find where to change it has been entangled with code for a number of other things. 

Look at https://mathics-development-guide.readthedocs.io/en/latest/extending/code-overview/top-level-eval-print.html#id4  (which I will to revise for my better understanding of this) and  https://mathics-development-guide.readthedocs.io/en/latest/extending/code-overview/boxes-forms-and-formats.html for some information on how this works

Specifically in the last document I write: 

> Right now, Form constraint on formatting is somewhat hardcoded. For example MathMLForm boxing 2D- Graphics force formatting to SVG. If instead the Form is TeXForm then an Aysmptote format is used.

From a Mathics Expression, the Form part converts one Mathics Expression into another kind of Mathics Expression (usually with more information bound in) which is closer to what is needed for output. Bounding Box information ("Boxing") is also added to the various components in preparation for display. 

After the Form stuff is done then you can finally call a formatter to get things into the right format needed. Calling the formatter before some sort of general Boxing generally can't be done. Probably in some cases it can, but not here for the reasons mentioned above.

You continue: 

> 
> Also I saw in the Network tab of Dev Tools the JSON still has MathML, then I checked the code and saw this:
> 
> ```python
> format = "System`MathMLForm"
> ```

Remember not only what I just wrote here in this comment but originally: 

> This causes it to evaluate the result in MathMLForm. (This is a real misnomer for having the Mathics Expression expanded into to a Mathics expression that is destined for Three.js.).

Disentangling this right now in a general way would be a major effort. But these branches do separate MathML form JSON a little bit more. 

You continue: 

> 
> (format.py line 89)
> 
> I guess another form should be created in Mathics core, e.g.: `` System`Graphics3DForm ``, shouldn't it?

The concepts I think are a bit muddy and there are gray areas so there is room for discussion, but I don't think so here. And it would be a bit of work to make that so which should be done for later when we clean all of this up. 

Think of a form as a container of lots of different kinds of fundamentally different _format_ stuff. So a XML/HTML document may have Math equations, HTML, graphics and animations in it. And it dictates for each of those some sort of overall properties, like what forms of graphics it can handle or whether or not it can nicely display Math equations or can do animations or not. (The text interfaces can't handle our graphics right now). 

Graphics3D hower is some kind of entity or primitive and such it needs a Graphics3DBox which will tell the boxers outside of it the information they need about bounding box. And the information outside can suggest various styling parameters, like this Graphics3DBox should be smallish because it will fit inside a figure of a certain size. And it will be told that it can only handle a certain kind of graphics format like json

>  Or maybe something built in Mathics Django backend to transform the Python object into a JSON?

This is a different and separate issue. Right now stuff from Mathics is coming back as a string, and I think that there should be a mechanism for information to come back as JSON. But this too is part of a bigger overhaul of everything. 

Right now although all of this is kludgy, what it does is set at inside mathics Django that different kinds of formatting is dictated by the top-level objects that are returned by evaluation (whether we get back text, graphics, mathml, etc.). 

This effort is a smallish effort of disentangling graphics specified in JSON from MathML. If it only does that, then this is a step forward.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I understand what you said. So let's go back to the code of `mathics.js`.

A `Graphics3D` response doesn't starts with "<script>".

Here is a sample of the reponse:
```json
<math display="block"><mstyle mathvariant="sans-serif"><mtable><mtr><mtd><graphics3d data="{&quot;elements&quot;: [{&quot;type&quot;: &quot;sphere&quot;, &quot;coords&quot;: [[[0, 0, 0], null]], &quot;radius&quot;: 1, &quot;faceColor&quot;: [1, 1, 1, 1]}], &quot;axes&quot;: {&quot;hasaxes&quot;: [false, false, false], &quot;ticks&quot;: [[[-1.0, -0.5, 0.0, 0.5, 1.0], [-0.9, -0.8, -0.7000000000000001, -0.6000000000000001, -0.4, -0.30000000000000004, -0.2, -0.1, 0.1, 0.2, 0.30000000000000004, 0.4, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9], [&quot;-1&quot;, &quot;-0.5&quot;, &quot;0&quot;, &quot;0.5&quot;, &quot;1&quot;]], [[-1.0, -0.5, 0.0, 0.5, 1.0], [-0.9, -0.8, -0.7000000000000001, -0.6000000000000001, -0.4, -0.30000000000000004, -0.2, -0.1, 0.1, 0.2, 0.30000000000000004, 0.4, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9], [&quot;-1&quot;, &quot;-0.5&quot;, &quot;0&quot;, &quot;0.5&quot;, &quot;1&quot;]], [[-1.0, -0.5, 0.0, 0.5, 1.0], [-0.9, -0.8, -0.7000000000000001, -0.6000000000000001, -0.4, -0.30000000000000004, -0.2, -0.1, 0.1, 0.2, 0.30000000000000004, 0.4, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9], [&quot;-1&quot;, &quot;-0.5&quot;, &quot;0&quot;, &quot;0.5&quot;, &quot;1&quot;]]], &quot;ticks_style&quot;: []}, &quot;extent&quot;: {&quot;xmin&quot;: -1.0, &quot;xmax&quot;: 1.0, &quot;ymin&quot;: -1.0, &quot;ymax&quot;: 1.0, &quot;zmin&quot;: -1.0, &quot;zmax&quot;: 1.0}, &quot;lighting&quot;: [{&quot;type&quot;: &quot;Ambient&quot;, &quot;color&quot;: [0.3, 0.2, 0.4]}, {&quot;type&quot;: &quot;Directional&quot;, &quot;color&quot;: [0.8, 0.0, 0.0], &quot;position&quot;: [2.0, 0.0, 2.0]}, {&quot;type&quot;: &quot;Directional&quot;, &quot;color&quot;: [0.0, 0.8, 0.0], &quot;position&quot;: [2.0, 2.0, 2.0]}, {&quot;type&quot;: &quot;Directional&quot;, &quot;color&quot;: [0.0, 0.0, 0.8], &quot;position&quot;: [0.0, 2.0, 2.0]}], &quot;viewpoint&quot;: [2.6, -4.8, 4.0]}" /></mtd></mtr></mtable></mstyle></math>
```

**Comment by rocky** [comment]
@TiagoCavalcanteTrindade I am sorry I wasn't clear. (And a lot of this is messy and complicated).

In format.py you will see an `if False:`. Change that to `if True:`.

Then the JS you will see in `mathics.js` is this: 

```
<script> <graphics3d data="{"elements": [{"type": "sphere", "coords": [[[0, 0, 0], null]], "radius": 1, "faceColor": [1, 1, 1, 1]}], "axes": {"hasaxes": [false, false, false], "ticks": [[[-1.0, -0.5, 0.0, 0.5, 1.0], [-0.9, -0.8, -0.7000000000000001, -0.6000000000000001, -0.4, -0.30000000000000004, -0.2, -0.1, 0.1, 0.2, 0.30000000000000004, 0.4, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9], ["-1", "-0.5", "0", "0.5", "1"]], [[-1.0, -0.5, 0.0, 0.5, 1.0], [-0.9, -0.8, -0.7000000000000001, -0.6000000000000001, -0.4, -0.30000000000000004, -0.2, -0.1, 0.1, 0.2, 0.30000000000000004, 0.4, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9], ["-1", "-0.5", "0", "0.5", "1"]], [[-1.0, -0.5, 0.0, 0.5, 1.0], [-0.9, -0.8, -0.7000000000000001, -0.6000000000000001, -0.4, -0.30000000000000004, -0.2, -0.1, 0.1, 0.2, 0.30000000000000004, 0.4, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9], ["-1", "-0.5", "0", "0.5", "1"]]], "ticks_style": []}, "extent": {"xmin": -1.0, "xmax": 1.0, "ymin": -1.0, "ymax": 1.0, "zmin": -1.0, "zmax": 1.0}, "lighting": [{"type": "Ambient", "color": [0.3, 0.2, 0.4]}, {"type": "Directional", "color": [0.8, 0.0, 0.0], "position": [2.0, 0.0, 2.0]}, {"type": "Directional", "color": [0.0, 0.8, 0.0], "position": [2.0, 2.0, 2.0]}, {"type": "Directional", "color": [0.0, 0.0, 0.8], "position": [0.0, 2.0, 2.0]}], "viewpoint": [2.6, -4.8, 4.0]}"/></script>
```

If you compare with the MathML, you'll see the data is no html escaped. It is in a more straightforward form to be used in Javascript. 

That doesn't mean this is valid Javascript. Just that this is the kind of idea that we could use. I would be grateful if you could turn this into valid Javascript so that in mathics.js it shows the three.js and we have a hope of adding controls to it if desired. 

Thanks.

**Comment by rocky** [comment]
One other very important thing. Make sure you are getting mathml-removal-in-3d-graphics from mathics core.

**Comment by TiagoCavalcanteTrindade** [comment]
> One other very important thing. Make sure you are getting https://github.com/Mathics/mathics/tree/json-graphics from Mathics core.

Yes I already made it, right now I pushed a commit to your branch.

Now right click shows the desired behavior.

![image](https://user-images.githubusercontent.com/62714153/121447191-8da4bf00-c96b-11eb-9dae-1f1ff710349c.png)

Also sorry for didn't understand what you meant before 😄.

**Comment by rocky** [comment]
Awesome!  @TiagoCavalcanteTrindade  this is really really nice - thanks!

**Comment by rocky** [comment]
I suppose we could/shod do the same things for SVG.

And down the pike start cleaning up all the mess here (which is a more long-term and bigger project).

**Comment by rocky** [comment]
I'm seeing a small number of problems now.  Things are generally more sluggish for 3D graphics, tick marks on axes to the left might go outside of the cell region, the last example in the testsuite doesn't work.

Probably using the `<script>` tag was a bad idea it could have been something like `<graphic3d>` and then other script tags wouldn't mess up.

But it is late and I have lots of other things to do, and this can all be fixed in due time. 

Overall I am really glad that we can start to break out of the silly put everything in MathML and jump through hoops in terms of making an image a glyph or whatever to make it work. (Turning it into a glyph may help things by caching images, but I suspect there is a more natural way to accomplish this.)
